-- +migrate Down
ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE users DROP COLUMN IF EXISTS first_name;
ALTER TABLE users DROP COLUMN IF EXISTS last_name;
ALTER TABLE users DROP COLUMN IF EXISTS is_shop_owner;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key;
